### ISSUE TITLE
Handling of # 

### ISSUE THREAD

**Issue by dzeruel** [psoukie/zipchord#33] opened 2022-12-18 23:20 UTC
**Describe the bug**
Authotkey interprets # as winkey therefore it cannot be used in the expanded text.

**Comment by psoukie** [comment] 2022-12-19 00:09
Thank you.  It seems to be working correctly for me in versions 1.8.2 and 1.8.3.  Have you tested this in the latest version? If so, can you give me an example of the chord and expanded text?

**Comment by psoukie** [comment] 2023-01-11 02:34
If you are still experiencing this issue, please let me know. Otherwise, I'm assuming this is working in both 1.9 and the 2.0 release candidate.

**Comment by psoukie** [comment] 2023-01-12 20:34
Duplicate of #27

**Closed by psoukie** 2023-01-12 20:34 UTC
Labels: duplicate
