### ISSUE TITLE
Shorthand types ~

### ISSUE THREAD

**Issue by Kentty0518** [psoukie/zipchord#205] opened 2024-05-31 02:34 UTC
I used to ~ to delete the space at the start of the shorthand in the situation that I start a text. I press space to trigger use of a shorthand then the shorthand can delete the space for me. with ver 2.1
I recently updated to ver 2.3.1 and now instead of deleting the space it types the ~ symbol.

E.G
dictionary
DX ~Dear X,

before
I type: 
space then Dx
output: 
Dear X,

now
I type: 
space then Dx
output: 
~Dear X,

Hope it make sense to you.
I usually use Shorthand function to put a paragraph of text in.

**Comment by psoukie** [comment] 2024-05-31 06:38
Sorry about this! When I rebuilt ZipChord in 2.1 and 2.2, I didn't have test coverage for a lot of the functionality, so there were some regressions. I'll include a test case for this so after it's fixed, it won't break again.

I am on a business trip this and next week with my work laptop only (where I don't have admin access), but I have remote access to another machine where I might be able to install AHK to fix this.

**Comment by psoukie** [comment] 2024-06-02 08:33
I managed to install the tools I need remotely, so will be able to go fix this.

As a workaround which might be handy even after fix, to force ZipChord to recognize shorthands after switching between apps etc., briefly press and release Shift. (So you could have the shorthand defined without ~ and do `Shift` `D` `X`)

**Comment by psoukie** [comment] 2024-06-13 20:48
This is now fixed in version 2.4. Because of the improvement that blocks shorthands for acronyms with uppercase letters such as "USD", do not type the shorthand with Shift for both `D` and `X`. 

You can also consider using the trick with brief pressing of `Shift` in situations where you switched to a new window or moved teh cursor, and then use a shorthand entry simply such as: 

`dx	Dear X,{Enter}`

But `~Dear X,` for the expanded text is now working correctly also.

**Closed by psoukie** 2024-06-13 20:48 UTC
Labels: bug
