### ISSUE TITLE
Timing and conditions to cast a chord

### ISSUE THREAD

**Issue by lmendez5** [psoukie/zipchord#24] opened 2022-12-16 16:08 UTC
Describe the bug

- Random failures with chords casting with no space before them or timing

- Check the pic below, green lines when the script behavior is as expected, and red ones when not `(chord=es)` you can notice the first seven attempts are OK. I know, there is a space before in the first testes, but they were written below normal speed. 

- Besides this, the restrict "chords while typing" option works fine for a while, then -suddenly- cast the chord. For a while I mean, like 5 min is working fine (full testing typing) and then, a couple of minutes  typing/or switch application, and then, shoot the chord! I set the detection delay at 65, and is fine for a while. Maybe something needs to be clear or resetead at the end of a loop or conditional. (just an idea)
![image](https://user-images.githubusercontent.com/95358420/208118030-89660f7e-e469-4ea4-9497-7c9a8f8c8317.png)

Useful Details
- Which settings do you have selected in the ZipChord settings?
![image](https://user-images.githubusercontent.com/95358420/208115965-b23e05c6-3f9a-46ce-8aed-00a23bb2b141.png)

- If the output is wrong, what is the sequence of keys pressed, the dictionary entry, and what text appears on the screen?

**Comment by psoukie** [comment] 2022-12-16 17:47
Thank you! There is definitely something going on here, but _some_ of the situations where the chord fires without a space are by design. For example, if you move your cursor, press Enter, click the mouse etc., the assumption is these are scenarios where a chord could be used next, and should be recognized.

But I agree it looks like something gets stuck in some scenarios and gets carried over. It is either a bug, or it could be related to the unfortunate fact that AutoHotkey does not activate an event for every key press and release, but even if it is that, there should be a workaround. I am going to debug this when I have time this weekend.

**Comment by psoukie** [comment] 2022-12-17 07:16
I tried but could not replicate the bug. In combination with the other issue you mentioned with "is:unread" (or something similar), I suspect there might be something causing the automated text output to be detected back in as input. (So when it writes out "El Salvador" it detects the space in the output, even though there are multiple other letters arriving near simultaneously, which would explain the random output.)

I could be wrong about this. To test it, could you please run a modified version of the script and type a few normal keys and then a chord? It will create a "debug.txt" in the same folder as the script and store the detected keypresses. If you type "test " and then the E+S chord, the output in debug.txt should be something like "~t~e~s~t~ ~e~s". Can you let me know if that's what you get, or you get something different?

The modified version is attached: [zipchord-debug.zip](https://github.com/psoukie/zipchord/files/10251155/zipchord-debug.zip)

And it's also here: https://github.com/psoukie/zipchord/blob/debugging/source/zipchord.ahk. I'm also attaching it in zip file if it's easier.

**Comment by psoukie** [comment] 2022-12-18 18:51
It's also possible that the [latest release](https://github.com/psoukie/zipchord/releases) works around this problem, because it changes how the chords are sent out. Please let me know what you find -- either with the new release, or what the output is with the debug version above. Thank you!

**Comment by lmendez5** [comment] 2022-12-21 02:25
Hi there! well, firstly, I am sorry for delayed response... I landed at _The Big Apple_ and it is a little crazy here! hehe, a lot of things to do and watch here! but, of course, my relax time is about some hobbies, and this is one of them. 

I did the test, so, this is the result: at the debug.txt `~t~e~s~t~e~s~t~e~s~t~w~a~t~e~s~t~2~e~s~t~e~s~t~3~ ~e~s~t~e~s~t~a~w~t~e~s~t~ ~e~a~t~e~s~t~4~w~a~t~e~s~t~ ~a~w` the output of this was as expected.

Also, I tried the last version and this is the result: `testEl Salvador testGuatemala`
I did it with a single word "Guatemala" in order to test that space in the chord response. So, wrong output with last version.

About the capitalization issue (Is:UnrEAD), is not happening at this moment! so, I will be attentive to this or other issues.

**Comment by psoukie** [comment] 2022-12-21 21:07
This is a great time to visit New York. Enjoy and stay warm!

I have been struggling to replicate this, so I created a more robust debugging feature in the [latest pre-released version](https://github.com/psoukie/zipchord/releases/tag/v.1.9.0)

If the problem still happens in this version, can you please turn on the "Log this session (debugging)" option on About tab, do a bit of typing that exhibits the error, re-open the ZipChord menu (which stops the debugging and opens the log so you can copy-paste the actual output), and send me the file?

Thank you!

**Comment by lmendez5** [comment] 2023-01-04 21:00
Hello there!! firstly, 🥳 **happy New Year!!** Secondly, I think this new version scope is fantastic!!!👌

These days are being a little busy. I have been using the last version and replying emails and writing some documents and I realized those suddenly unwanted chords triggered. Today, I had some time to _log_ a session and I did a few chords in order you have a log with more regular typing. 

Well, at weekend I will try to snoop into the script and _log_, in order to do some tests and check if I can implement some of the features I had in my local version. The file with the log is [here](https://drive.google.com/file/d/1EdS2OkXjrKrefnQh_PqB160njNiEukRs/view?usp=sharing). I hope it could help to the cause! 

Take care!!

**Comment by psoukie** [comment] 2023-01-04 21:17
Thank you, and happy New Year to you too!

Thank you for the log file -- next time, please also copy the actual text that was produced in the editor, and paste it at the top of the log file. I can then hunt for a discrepancy between the events in the app and the actual output.

(So the log can be enabled for only a short portion, if the bug is something that you can alway reproduce. But I know some bugs appear more random.)

I'm back to my regular work schedule, but I might be able to get a Beta of 2.0 out tonight or tomorrow.

**Comment by psoukie** [comment] 2023-01-04 21:26
I forgot to say about "implementing some of the features I had in my local version" -- let me know if something general is missing.

For the keyboard languages/layouts, people can now use the Customize button for "Keyboard and language". (And list the keyboard keys under "All keys". The details on this are in the Readme page.)

If there's something else, let me know!

**Comment by lmendez5** [comment] 2023-01-04 23:11
Ok!! I will try to do another test and copy the original text at the header of the log file.

The feature for customize languages and layouts... works like a charm! great one!

On the other hand, about the feature on my former local version, well, I get used to press the "_custom modifier key_", so meanwhile the version is being debugging I was thinking about get this little thing, but I don't want to lose the new features like Shifting, blank spaces, etc. I tried to use another key as a modifier, but I need the specific PrintScreen key, because it doesn't cast or do anything. I tried to use the reachable Spacebar, but sometimes I get an additional space. The thing is when I am writing in a hurry and I get a chord, well, I get a little nervous! 😬 hahaha

As an adicional comment, there is a green alert when the script is detecting the keys for a chord while typing and not launching it, and it has good success rate!!. Not big deal, but maybe you can enable it just for logging mode? As an example, here is the one with my chord `cl = cliente`

![image](https://user-images.githubusercontent.com/95358420/210662560-8124a064-c1c0-494e-bdb4-55827bf7dafc.png)

Thank you and when I have the new test, I will post it here as before.

**Comment by psoukie** [comment] 2023-01-05 07:14
Thank you for telling me about this! It wasn't easy but a good challenge to figure out how to support special keys, such as PrintScreen.

An example on how to use this feature is here: https://github.com/psoukie/zipchord/issues/90#issuecomment-1371763291  

I tested this and included it in the [Beta release](https://github.com/psoukie/zipchord/releases/tag/2.0.0-beta)

To get rid of the green hints, uncheck the "Show hints for chords and shorthands" option on Detection tab.

I am going to close this issue because it mixed a lot of topics, but will check the log, and if you run into the problem with incorrect triggering of chords again, please open a new issue. 

Thank you again for helping me make ZipChord better!

**Closed by psoukie** 2023-01-05 07:14 UTC
Labels: bug, question
